# -*- coding: utf-8 -*-

{
    "name" : "The Hub",
    "version" : "15.0.0.0",
    'category' : "Customization",
    "summary" : "The Hub",
    "description": """
                 The Hub customization
    """,
    "author" : "Arpit Goel",
    "website" : "",
    "depends" : ["auth_signup", "portal", "stock","partner_credit_limit"],
    "data" :[
        'security/ir.model.access.csv',
        'data/mail_activity_data.xml',
        'data/email_template.xml',
        'data/ir_sequence_data.xml',
        'data/cron_job_data.xml',
        'data/service_product_date.xml',
        'data/action_server.xml',
        'views/res_config_settings_views.xml',
        'views/signup_form.xml',
        'views/res_partner_views.xml',
        'views/warehouse_receive_order_views.xml',
        'views/workorder_views.xml',
        'views/customer_portal_template.xml',
        'views/workorder_portal_template.xml',
        'views/product_portal_templates.xml',
        'views/portal_templates.xml',
        'views/send_inventory_portal_templates.xml',
        'views/wro_portal_templates.xml',
        'views/analytics_templates.xml',
        'views/stock_quant_inherit.xml',
        'views/helpdesk_ticket_inherited_view.xml',
        'views/three_pl_company_view.xml',
        'views/three_pl_template.xml',
        'views/inventory_status_portal_inherit.xml',
        'views/packing_type_view.xml',
        'views/box_size_view.xml',
        'views/billing_type_view.xml',
        'views/template_my_analytic.xml',
        'views/my_invoice_template.xml',
        'views/wallet_transaction_template.xml',
        'views/template_my_account.xml',
        'views/on_hold_receiveing_template.xml',
        'views/storage_box_view.xml',
        'views/product_template_inherit.xml',
        'views/dashboard_record_view.xml',
        'views/reorder_level_noti_view.xml',
        'views/notification_reorder_level_view_portal.xml',
        'views/top_selling_products.xml',

        'reports/report_paperformat.xml',
        'reports/package_lable_view.xml',
        'reports/package_lable_template.xml',
        'reports/shipping_label.xml',
        'reports/shipping_label_template.xml',
        'reports/wo_manifest_views.xml',
        'reports/wo_manifest_template.xml',
        'wizard/wizard_update_view.xml',
        'wizard/wizard_add_packaging.xml',
        'wizard/bulk_import_lines_view.xml',
        'wizard/wo_line_import_view.xml',
        'wizard/update_location_view.xml',
        'wizard/scanned_package_number_wo_view.xml'
    ],
    "auto_install": False,
    "installable": True,
    'assets': {
        'web.assets_frontend': [
            'ag_the_hub/static/src/js/graph/apexcharts.css',
            'ag_the_hub/static/src/js/graph/apexcharts.min.js',
            'ag_the_hub/static/src/css/custom.css',
            'https://cdn.plot.ly/plotly-2.26.0.min.js',
            # 'ag_the_hub/static/src/css/app_min.css',
            # 'ag_the_hub/static/src/css/icons_min.css',
            
            'ag_the_hub/static/src/js/product_search.js',
            'ag_the_hub/static/src/js/workorder.js',
            'ag_the_hub/static/src/js/custom.js',
            'ag_the_hub/static/src/js/multiselect.js',
            'ag_the_hub/static/src/js/inventory_status_export.js',
            'ag_the_hub/static/src/js/wro_status_export.js',
            'ag_the_hub/static/src/js/wo_export_status.js'
        ],
        'web.assets_qweb': [
            'ag_the_hub/static/src/xml/template.xml',
        ],
    },
    'license': 'LGPL-3',
}

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
