from . import res_company
from . import res_config_settings
from . import box_size
from . import res_partner
from . import product
from . import warehouse_receive_order
from . import workorder
from . import account_move
from . import stock_picking_inherit
from . import helpdesk_ticket_inherit
from . import three_plcompany
from . import stock_quant_inherit
from . import packing_type
from . import billing_type
from . import storage_box
from . import dashboard_record
from . import reorder_level_notification
