# -*- coding: utf-8 -*-

{
    'name': "Multi Branch",
    'version': "15.0.1.0.1",
    'summary': """ This module provide functionality Multi Branch for, sales, purchase, accounting and inventory.""",
    'description': """This module provide functionality Multi Branch for, sales, purchase, accounting and inventory""",
    'author': "Arpit Goel",
    'maintainer': "Arpit Goel",
    'website': "",
    'category': 'Tools',
    'depends': ['base', 'sale_management', 'sale_stock', 'purchase_stock', 'purchase_requisition', 'stock_account'],
    'data': [
        'security/multi_branch_security.xml',
        'security/ir.model.access.csv',
        'views/res_branch_views.xml',
        'views/product_template_views.xml',
        'views/res_partner_views.xml',
        'views/sale_order_views.xml',
        'views/purchase_order_views.xml',
        'views/res_users_views.xml',
        'views/cost_category_views.xml',
        'views/management_fee_views.xml',
        'views/stock_picking_views.xml',
        'views/account_move_views.xml',
        'views/account_payment_views.xml',
        'views/account_journal.xml',
        'views/account_views.xml',
        'views/stock_warehouse_views.xml',
        'views/report_template.xml',
        'data/ir_module_category_data.xml',
    ],
    'installable': True,
    'application': False,
    'license': 'LGPL-3',
}
